// GET request to get a reminder

GET http://localhost:3000/getReminder
Content-Type: application/json

{
    "reminder": "Wake up Sid",
    "remindAt": "new Date.now().toString()" 
}

###

// POST request to add a reminder

POST  http://localhost:3000/addReminder
Content-Type: application/json

{
    "reminder": "Wake up sid",
    "remindAt": "{{$datetime rfc1123|iso8601 []}}"
}

###

// GET request to get all reminders

GET http://localhost:3000/getAllReminders

###

// DELETE request to delete a reminder

DELETE  http://localhost:3000/6333cefe4d374ecab80f660a


