// GET request to get a reminder

GET http://localhost:3000/getReminderByName
Content-Type: application/json

{
    "reminder": "Wake up Sid",
    "remindAt": "new Date.now().toString()" 
}

###

// POST request to add a reminder

POST  http://localhost:3000/addReminder
Content-Type: application/json

{
    "reminder": "Wake up sid",
    "remindAt": "{{$datetime rfc1123|iso8601 []}}"
}

###

// GET request to get all reminders

GET http://localhost:3000/getAllReminders

###
// GET request to get all reminders that have been reminded

GET http://localhost:3000/getAllReminded

###

// DELETE request to delete a reminder by Id

DELETE  http://localhost:3000/deleteById/6333e8428175961a979fca25


