
GET http://localhost:3000/getReminder
Content-Type: application/json

{
    "reminder": "Wake up Sid,
    "remindAt": "new Date.now().toString()" 
}

###

POST  http://localhost:3000/addReminder
Content-Type: application/json

{
    "reminder": "Wake up sid",
    "remindAt": "{{$datetime rfc1123|iso8601 []}}"
}

###

GET http://localhost:3000/getAllReminders

###

DELETE  http://localhost:3000/6332e032a96d322f5a2ed4ad

